//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAR.TeamManager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class audit
    {
        public int ID { get; set; }
        public Nullable<bool> bAuditState { get; set; }
        public string vcTeacherReturn { get; set; }
        public Nullable<System.DateTime> dAuditTime { get; set; }
        public Nullable<int> iActivitieApplicationID { get; set; }
        public Nullable<int> iHonorID { get; set; }
        public Nullable<int> iTeamApplicationID { get; set; }
        public Nullable<bool> IsDel { get; set; }
    }
}
