//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAR.TeamManager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class honor
    {
        public int ID { get; set; }
        public string vcHonorName { get; set; }
        public Nullable<System.DateTime> dSubmitTime { get; set; }
        public string vcHonorIntroduce { get; set; }
        public string vcGuideTeacher { get; set; }
        public string vcHonorSubmitAddress { get; set; }
        public string vcHonorSliderAddress { get; set; }
        public string vcPreviewAddress { get; set; }
        public string vcNetConnectAddress { get; set; }
        public string vcDownLoadAddress { get; set; }
        public string vcTechnicalType { get; set; }
        public Nullable<bool> bReviewOfWorks { get; set; }
        public Nullable<int> iTeamID { get; set; }
        public Nullable<bool> bDownLoadUnable { get; set; }
        public Nullable<bool> IsDel { get; set; }
    }
}
