//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAR.TeamManager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class personalinformation
    {
        public int ID { get; set; }
        public Nullable<int> iUserID { get; set; }
        public string vcName { get; set; }
        public string cPhone { get; set; }
        public string vcGender { get; set; }
        public Nullable<System.DateTime> dBirthday { get; set; }
        public string vcWeChat { get; set; }
        public string vcEmail { get; set; }
        public string vcQQ { get; set; }
        public string vcHobby { get; set; }
        public string vcPersonalIntroduce { get; set; }
        public string vcAddress { get; set; }
        public string vcMajor { get; set; }
        public string vcGrade { get; set; }
        public Nullable<bool> IsDel { get; set; }
    }
}
