//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAR.TeamManager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class teamapplication
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> dApplyTime { get; set; }
        public string vcTeamType { get; set; }
        public string vcTeamApplicationLocation { get; set; }
        public Nullable<int> iApplyNumber { get; set; }
        public Nullable<bool> bApplyState { get; set; }
        public string vcTeamExpectResult { get; set; }
        public string vcTeamActivityPlan { get; set; }
        public string vcTeamProSituation { get; set; }
        public string vcApplicantIntroduce { get; set; }
        public Nullable<bool> IsDel { get; set; }
    }
}
